// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYQ63HxZ8MxYG0adTGLp2K2sAmYgyVoeM',
    appId: '1:610577406683:web:49852f73363f3031d84afe',
    messagingSenderId: '610577406683',
    projectId: 'aura-84408',
    authDomain: 'aura-84408.firebaseapp.com',
    storageBucket: 'aura-84408.firebasestorage.app',
    measurementId: 'G-F5EWZC97BM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk2s0flRwS3wV_a7_G-QpJRJR1xihTKYM',
    appId: '1:610577406683:android:730778e8980aa723d84afe',
    messagingSenderId: '610577406683',
    projectId: 'aura-84408',
    storageBucket: 'aura-84408.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmGeTm7yIxHc0hogScxYe9O6RRRsq0-WM',
    appId: '1:610577406683:ios:7039125ec0ac7f4cd84afe',
    messagingSenderId: '610577406683',
    projectId: 'aura-84408',
    storageBucket: 'aura-84408.firebasestorage.app',
    iosBundleId: 'com.example.aura',
  );
}
